// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelSpotFinder.Api.Data;

#nullable disable

namespace TravelSpotFinder.Api.Data.Migrations
{
    [DbContext(typeof(TravelSpotDbContext))]
    [Migration("20260417074802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Booking", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("booking_code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("cancellation_reason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("cancelled_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("confirmation_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("confirmed_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("departure_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("discount_amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("guests")
                        .HasColumnType("int");

                    b.Property<string>("meeting_point_snapshot")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("notes")
                        .HasColumnType("longtext");

                    b.Property<int?>("package_id")
                        .HasColumnType("int");

                    b.Property<string>("payment_method")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("pickup_address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("pickup_requested")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("qr_value")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<decimal?>("refund_amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("rejection_reason")
                        .HasColumnType("longtext");

                    b.Property<int>("room_count")
                        .HasColumnType("int");

                    b.Property<int?>("room_id")
                        .HasColumnType("int");

                    b.Property<int>("spot_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("subtotal_price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ticket_code")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<decimal?>("total_price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("tour_days")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<int?>("voucher_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("booking_code")
                        .IsUnique();

                    b.HasIndex("departure_id");

                    b.HasIndex("package_id");

                    b.HasIndex("room_id");

                    b.HasIndex("spot_id");

                    b.HasIndex("ticket_code")
                        .IsUnique();

                    b.HasIndex("user_id");

                    b.HasIndex("voucher_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("icon")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Favorite", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("spot_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("spot_id");

                    b.HasIndex("user_id");

                    b.HasIndex("user_id", "spot_id")
                        .IsUnique();

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Payment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("booking_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("due_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("paid_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("refunded_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("transaction_code")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("booking_id")
                        .IsUnique();

                    b.HasIndex("transaction_code")
                        .IsUnique();

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Review", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<int>("spot_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("spot_id");

                    b.HasIndex("user_id");

                    b.HasIndex("user_id", "spot_id")
                        .IsUnique();

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.SearchHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("keyword")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<double?>("latitude")
                        .HasColumnType("double");

                    b.Property<double?>("longitude")
                        .HasColumnType("double");

                    b.Property<DateTime>("searched_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("keyword");

                    b.HasIndex("user_id");

                    b.ToTable("search_histories", (string)null);
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Spot", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<double>("average_rating")
                        .HasColumnType("double");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("image_url")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<double>("latitude")
                        .HasColumnType("double");

                    b.Property<double>("longitude")
                        .HasColumnType("double");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("opening_hours")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("ticket_price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.HasIndex("city");

                    b.HasIndex("created_by");

                    b.HasIndex("latitude", "longitude");

                    b.ToTable("spots", (string)null);
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.SpotDeparture", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("booked_count")
                        .HasColumnType("int");

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<string>("confirmation_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("end_time")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("spot_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("spot_id");

                    b.HasIndex("start_time");

                    b.ToTable("spot_departures", (string)null);
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.SpotImage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("is_primary")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("spot_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("spot_id");

                    b.ToTable("spot_images", (string)null);
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.SpotPackage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<int?>("duration_minutes")
                        .HasColumnType("int");

                    b.Property<int>("free_cancel_before_hours")
                        .HasColumnType("int");

                    b.Property<string>("meeting_point")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("pickup_area")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("pickup_included")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("pickup_note")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("refund_percent_after")
                        .HasColumnType("int");

                    b.Property<int>("refund_percent_before")
                        .HasColumnType("int");

                    b.Property<int>("spot_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("spot_id");

                    b.ToTable("spot_packages", (string)null);
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.SpotRoom", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<int>("free_cancel_before_hours")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("refund_percent_after")
                        .HasColumnType("int");

                    b.Property<int>("refund_percent_before")
                        .HasColumnType("int");

                    b.Property<int>("spot_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("spot_id");

                    b.ToTable("spot_rooms", (string)null);
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("avatar_url")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Voucher", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("max_discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("min_booking_amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("usage_limit")
                        .HasColumnType("int");

                    b.Property<int>("used_count")
                        .HasColumnType("int");

                    b.Property<decimal>("value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.ToTable("vouchers", (string)null);
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Booking", b =>
                {
                    b.HasOne("TravelSpotFinder.Api.Data.Entities.SpotDeparture", "departure")
                        .WithMany("bookings")
                        .HasForeignKey("departure_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelSpotFinder.Api.Data.Entities.SpotPackage", "package")
                        .WithMany("bookings")
                        .HasForeignKey("package_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelSpotFinder.Api.Data.Entities.SpotRoom", "room")
                        .WithMany("bookings")
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelSpotFinder.Api.Data.Entities.Spot", "spot")
                        .WithMany("bookings")
                        .HasForeignKey("spot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelSpotFinder.Api.Data.Entities.User", "user")
                        .WithMany("bookings")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelSpotFinder.Api.Data.Entities.Voucher", "voucher")
                        .WithMany("bookings")
                        .HasForeignKey("voucher_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("departure");

                    b.Navigation("package");

                    b.Navigation("room");

                    b.Navigation("spot");

                    b.Navigation("user");

                    b.Navigation("voucher");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Favorite", b =>
                {
                    b.HasOne("TravelSpotFinder.Api.Data.Entities.Spot", "spot")
                        .WithMany("favorites")
                        .HasForeignKey("spot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelSpotFinder.Api.Data.Entities.User", "user")
                        .WithMany("favorites")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("spot");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Payment", b =>
                {
                    b.HasOne("TravelSpotFinder.Api.Data.Entities.Booking", "booking")
                        .WithOne("payment")
                        .HasForeignKey("TravelSpotFinder.Api.Data.Entities.Payment", "booking_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("booking");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Review", b =>
                {
                    b.HasOne("TravelSpotFinder.Api.Data.Entities.Spot", "spot")
                        .WithMany("reviews")
                        .HasForeignKey("spot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelSpotFinder.Api.Data.Entities.User", "user")
                        .WithMany("reviews")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("spot");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.SearchHistory", b =>
                {
                    b.HasOne("TravelSpotFinder.Api.Data.Entities.User", "user")
                        .WithMany("searchHistory")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Spot", b =>
                {
                    b.HasOne("TravelSpotFinder.Api.Data.Entities.Category", "category")
                        .WithMany("spots")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelSpotFinder.Api.Data.Entities.User", "creator")
                        .WithMany("spots_created")
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("creator");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.SpotDeparture", b =>
                {
                    b.HasOne("TravelSpotFinder.Api.Data.Entities.Spot", "spot")
                        .WithMany("departures")
                        .HasForeignKey("spot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("spot");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.SpotImage", b =>
                {
                    b.HasOne("TravelSpotFinder.Api.Data.Entities.Spot", "spot")
                        .WithMany("images")
                        .HasForeignKey("spot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("spot");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.SpotPackage", b =>
                {
                    b.HasOne("TravelSpotFinder.Api.Data.Entities.Spot", "spot")
                        .WithMany("packages")
                        .HasForeignKey("spot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("spot");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.SpotRoom", b =>
                {
                    b.HasOne("TravelSpotFinder.Api.Data.Entities.Spot", "spot")
                        .WithMany("rooms")
                        .HasForeignKey("spot_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("spot");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Booking", b =>
                {
                    b.Navigation("payment");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Category", b =>
                {
                    b.Navigation("spots");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Spot", b =>
                {
                    b.Navigation("bookings");

                    b.Navigation("departures");

                    b.Navigation("favorites");

                    b.Navigation("images");

                    b.Navigation("packages");

                    b.Navigation("reviews");

                    b.Navigation("rooms");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.SpotDeparture", b =>
                {
                    b.Navigation("bookings");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.SpotPackage", b =>
                {
                    b.Navigation("bookings");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.SpotRoom", b =>
                {
                    b.Navigation("bookings");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.User", b =>
                {
                    b.Navigation("bookings");

                    b.Navigation("favorites");

                    b.Navigation("reviews");

                    b.Navigation("searchHistory");

                    b.Navigation("spots_created");
                });

            modelBuilder.Entity("TravelSpotFinder.Api.Data.Entities.Voucher", b =>
                {
                    b.Navigation("bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
